#############################################################################################
#
# File name : top_simulate.do
# Created on: Fri Jul 18 23:47:57 IST 2025
#
# Script automatically generated by Aldec Tcl Store app 1.39 for 'behavioral' simulation,
# in Vivado v2025.1 (64-bit) for Riviera-PRO simulator.
#
#############################################################################################
vsim -sv_seed random +access +r +m+top +UVM_VERBOSITY=UVM_DEBUG +UVM_OBJECTION_TRACE -L unisims_ver -L unimacro_ver -L secureip -L xpm -L axi_datamover_v5_1_37 -L axi_sg_v4_1_21 -L axi_cdma_v4_1_35 -L xil_defaultlib -O0 xil_defaultlib.top xil_defaultlib.glbl -l sim_txt.log \
-do "log -r /*;
     add wave -rec sim:/top/m_axi_lite_if/*;
     add wave -rec sim:/top/s_axi_if/*;
     add wave -rec sim:/top/s_axi_sg_if/*;
     run -all;"















#-do "add wave -rec -position insertpoint sim:/top/m_axi_lite_if/*; add wave -rec -position insertpoint sim:/top/s_axi_if/*; add wave -rec -position insertpoint sim:/top/s_axi_sg_if/*; run -all"

#-do "add wave -rec -position insertpoint sim:/top/dut/*; run -all"

#-do "add wave -rec -position insertpoint sim:/top/m_axi_if/*; \
#     add wave -rec -position insertpoint sim:/top/m_axi_sg_if/*; \
#     add wave -rec -position insertpoint sim:/top/s_axi_lite_if/*; \
#     run -all"

#-do "run -all"

#wave *

#+UVM_OBJECTION_TRACE 

#run 1000ns
# -O5 to -O0
# +m+top to +top
